### ISSUE TITLE
StaticResource not found

### ISSUE THREAD

**Issue by JRenseler** [UXDivers/Gorilla-Player-Support#327]
Hello, 

I'm testing the Gorilla-Player with Xamarin Forms and Prism with DryIoC. 

Whenever I open a page using StaticResources (defined in the App.xaml) the Gorilla Player displays an error message (StaticResource not found for key ...). 

I'm using the Gorilla SDK,  below my code to load the application. 
```
  LoadApplication(UXDivers.Gorilla.Droid.Player.UseApplication(new App(new AndroidInitializer(this, Logger)), this, new UXDivers.Gorilla.Config("Good Gorilla")
                                                                           .RegisterAssemblyFromType<Prism.IActiveAware>() // Prism
                                                                          .RegisterAssemblyFromType<PrismApplicationBase>()
                                                                          .RegisterAssemblyFromType<Prism.DryIoc.PrismApplication>() // Prism.DryIOC                                                                         .RegisterAssemblyFromType<Prism.DryIoc.DryIocContainerExtension>()
                                                                          .RegisterAssemblyFromType<App>()));
```
Here my App.xaml

```
prism:PrismApplication xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:prism="clr-namespace:Prism.DryIoc;assembly=Prism.DryIoc.Forms"
             x:Class="Qits.Bp.Mobile.App">
    <Application.Resources>

        <ResourceDictionary>
<Style TargetType="Label" ApplyToDerivedTypes="True">
                <Setter Property="TextColor" Value="{StaticResource PrimaryText}" />
            </Style>
        </ResourceDictionary>
    </Application.Resources>
</prism:PrismApplication>
```

Did I miss some initialization? 

Thanks for your help in advance!

**Comment by Umar3x** [comment]
Hello,

Same prob a #313 discussion. @LeoHere have you got any clews now ? Thanks :)

**Comment by geoffreys** [comment]
Can confirm same issue here. In my case App.xaml merges in a bunch of other dictionaries (eg colours, styles, fontstyles, etc).  Net result in Gorilla is StaticResource XXXXX not found, and page can't render.

Remove the StaticResource binding and the page renders correctly.

Prism and Unity in my case, if it matters. Gorilla 1.5, no updates available.

**Comment by IoTFier** [comment]
Hi @LeoHere , I am facing same issue with Prism.DryIoC v 7.1.x; XF 3.4 while trying to preview my XAML via Gorilla Player (built using Prism.DryIoC v7.1.x). My XAML files are in a XF App project that has reference to the new beta version Gorilla Auto Config Nuget package.

Your help will be appreciated.

![image](https://user-images.githubusercontent.com/26844611/50751828-148c6500-1211-11e9-8d7c-c5dd296bfda6.png)

**Comment by JRenseler** [comment]
Any news and ideas on this? 
We would really like to use Gorilla Player, but are blocked by this issue. 

Is there anything we could do to sort it out? Would a demo project be helpful?

**Comment by Umar3x** [comment]
Not for now I stoppped using gorilla cause of this issue ;( as my app goes bigger and bigger. @LeoHere have you digged into  this ? Thanks.

**Comment by Umar3x** [comment]
@geoffreys  I'm not sure its not maintained anymore but it seems that's this prob is difficult to investigate for maintainers .. I wish I could help but for now I can't.

**Comment by IoTFier** [comment]
@Umar3x - I pulled up that preview to give any possible hint to @LeoHere and Gorilla team in case... just like in https://github.com/UXDivers/Gorilla-Player-Support/issues/158
Besides - here is the another XAML page preview that supports our common issue .. 
![image](https://user-images.githubusercontent.com/26844611/52123510-f8030300-25eb-11e9-9222-81a07bc55a11.png)

**Comment by LeoJHarris** [comment]
@LeoHere This is seriously killing previewing our project. Can we please get some update / feedback on this issue if there is some temp solution or whether even its being actively investigated please? Would be such a shame to see Gorilla player fall by the way side.

**Comment by LeoJHarris** [comment]
@LeoHere Seems to be an issue with referencing StaticResource in code rather then xaml, in my example I have a ViewCell with a backing xaml.cs file and some StaticResource is being referenced in there.

**Comment by IoTFier** [comment]
@LeoHere, I am getting the StaticResource not found error while using Prism based MVVM + Grial Starter project . Any help is addressing this issue? 

Thanks

**Comment by lnaie** [comment]
Having the same issue. Moving the global resources locally solves it but, well, it should be fixed.
Anyone knows why does it happen?

**Comment by rsuk** [comment]
Any update / timeline for an update on this one? I am also in the situation where it has killed dead my ability to use Gorilla in my latest project :(

**Comment by jadenrogers** [comment]
@lnaie @rsuk I also had this issue, clean and build didn't resolve it. Not sure where the issue lay, I ended up downgrading the server and SDK to 1.5. Tested all fine. 
Upgraded server to 1.5.2 - Still ran fine
Upgraded SDK to 1.5.2 - Still ran fine 

Something to try is maybe remove the app completely from the simulator rather than publishing over the top.
 
If you still have issues post your gorillaPlayer.log file after changing the verbosity to debug.

**Comment by thegeox** [comment]
I used to had the StaticResource not found problem. Handled in two different ways. First referenced my Global Style xaml in the page I needed the style to show (just remove when no need them anymore). Second, if in my style a key wasn't found, I solved it changing the StaticResource for DynamicResource. It is just a temporally workaround. Waiting for Hot Reload to see I things get better.
