### ISSUE TITLE
Error occurred while setting Gorilla Target XAML. 

### ISSUE THREAD

**Issue by supreettare** [UXDivers/Gorilla-Player-Support#51]
Hi, 
I got gorilla player working with your sample solution, however when I try to use in my primary project, I get this error.
![image](https://cloud.githubusercontent.com/assets/284847/13450425/268471d4-e05b-11e5-95ce-65ae5014cc5a.png)

Any workarounds? 
Thanks

**Comment by supreettare** [comment]
Logs show this error: 

error: Xaml processing error Summary:\"Fail to open project file\"; Message:\"Could not open project file \"<MyProjectDirectory>\\City.Site\" (EISDIR, illegal operation on a directory).\" processingIssue=true, issueType=error, position=null, area=Gral, scope=Sol, name=Error, message=EISDIR, illegal operation on a directory, stack=Error: EISDIR, illegal operation on a directory\n    at Object.fs.readSync (fs.js:498:15)\n    at Object.fs.readFileSync (fs.js:323:18)\n    at Object.parser._loadProject (C:\\Program Files (x86)\\Gorilla Player\\resources\\SolutionParser.js.jx:322:34)\n    at Object.<anonymous> (C:\\Program Files (x86)\\Gorilla Player\\resources\\SolutionParser.js.jx:298:26)\n    at Object.<anonymous> (C:\\Program Files (x86)\\Gorilla Player\\resources\\SolutionParser.js.jx:430:21)\n    at Object.tryCatcher (C:\\Program Files (x86)\\Gorilla Player\\resources\\node_modules\\bluebird\\js\\main\\util.js.jx:25:23)\n    at Promise._settlePromiseFromHandler (C:\\Program Files (x86)\\Gorilla Player\\resources\\node_modules\\bluebird\\js\\main\\promise.js.jx:506:31)\n    at Promise._settlePromiseAt (C:\\Program Files (x86)\\Gorilla Player\\resources\\node_modules\\bluebird\\js\\main\\promise.js.jx:580:18)\n    at Async._drainQueue (C:\\Program Files (x86)\\Gorilla Player\\resources\\node_modules\\bluebird\\js\\main\\async.js.jx:127:12)\n    at Async._drainQueues (C:\\Program Files (x86)\\Gorilla Player\\resources\\node_modules\\bluebird\\js\\main\\async.js.jx:132:10)\n    at Async.drainQueues (C:\\Program Files (x86)\\Gorilla Player\\resources\\node_modules\\bluebird\\js\\main\\async.js.jx:14:14)\n    at process._tickCallback (node.js:803:1), contextInstanceId=3, targetId=0, sampleDataId=0\n","timestamp":"2016-03-02T04:24:09.846Z"}

note: I have masked the exact location of the project in my machine with <MyProjectDirectory> above

My Solution Architecture has following projects: 
PCL
Android 
iOS 
WindowsPhone
AnotherPCLForBusinessLogic
WebAPIMVCProject (Azure mobile services with Dot Net backend) 
WebSite (This is a plain asp.net website for the app we are developing) this web site project seems to be creating issues as you can see in your logs. 
Removing the web site project from solution works, but not ideal for me. I prefer keeping every project I need under one solution. 

Will be glad if you could look into it please. 
Thanks

**Comment by jpbrocca** [comment]
Hi @supreettare, hope you are doing fine.
We will review this issue soon and let you know.

Thanks,
JP

**Comment by supreettare** [comment]
Thanks JP, 
Meanwhile after the site is removed. The player is working flawless. :) 
Does not appear to work with TabbedPages, Custom Controls or custom renderers for now, but does what it says. 
Cool stuff. 

Thanks
ST

**Comment by jpbrocca** [comment]
You are welcome @supreettare :)

Yes, TabbedPages are not at 100% but you certainly can preview custom renderers and complex things through [Gorilla SDK](https://github.com/UXDivers/Gorilla-Player-Support-And-Issues/wiki/Gorilla-SDK).

Cheers,
JP

**Comment by supreettare** [comment]
Awesome, I was not aware of that. Will give tat a try now. 

BTW That SDK page can do with a few changes here & there (English & Grammatical) .Do you mind if I jot it down in my own words on a word doc & share it with you? If you like the changes, you may well go ahead & update the content? 

ST

**Comment by jpbrocca** [comment]
YES PLEASE @supreettare ! :)

Thanks a lot!

Best,
JP

**Comment by supreettare** [comment]
Fantastic. I will do it :) will update you here.

**Comment by jpbrocca** [comment]
Awesome!
Thanks in advance @supreettare :)

**Comment by supreettare** [comment]
The steps mentioned in that link are for Droid, I assume the same works with iOS?

**Comment by jpbrocca** [comment]
Yes, similar steps for iOS.

**Comment by supreettare** [comment]
Thanks 
One more query, 
this LoadApplication code 

LoadApplication (Player.Droid.Player.CreateApplication(ApplicationContext, new Player.Config("Good Gorilla")));

Should it go before the default LoadApplication(new App()); or after it, or should it replace the default LoadApplication? 

Thanks 
ST

**Comment by supreettare** [comment]
I figured it does not replace it, you are loading the player. So it has to go before the default LoadApplication call. 
I also notice you need to install [https://www.nuget.org/packages/SocketIoClientDotNet/0.9.12](a nuget package) to be able to compile it fine.

**Comment by LeoHere** [comment]
Hi @supreettare,

Thanks for the feedback and help!!

The LoadApplication line must replace the LoadApplication (new App...). Regarding dependencies, in the next release we will be moving SDK and Common dependencies to a nuget package in order to simplify this process.

**Comment by supreettare** [comment]
Hi @LeoHere 

I am stuck. 
I followed all steps, replaced the LoadApplication with the default one & now when I run the app on a droid it says 

Looking for a server named Good Gorilla please wait.. Nothing happens after that. If I go for the manual option, which gorilla server IP should I key in? 

Thanks 
ST

**Comment by LeoHere** [comment]
Is the host app up and running in your desktop machine? (you could test it by visiting http://localhost:9014/, where you should see an about page)

If it is up and running, it should be automatically discovered by the player executing in the device (still there are some issues with discovery in windows). Your current setup is expecting a host app with the name "Good Gorilla" and probably your host app has a different name. You can get the name from the about page. Still, the player should display a list with all the host apps discovered so far.

If automatic discovery does not work, the about page also says the IP addresses where gorilla is listening.

**Comment by jpbrocca** [comment]
To get the info, right clic on Gorilla icon, then go to "About Gorilla..." option:

![image](https://cloud.githubusercontent.com/assets/15996999/13457821/d92b6350-e048-11e5-9d7d-4b94163ea95b.png)

![image](https://cloud.githubusercontent.com/assets/15996999/13457837/e7cf00f6-e048-11e5-96bf-2a6880e45e50.png)

**Comment by supreettare** [comment]
I figured that out before the answer :) 
You really need to update your documentation to avoid confusion. 

This time, while using the SDK in my Droid & iOS & replacing Load Application call, I am actually loading an instance of gorilla player under the name & con of my application. 

This in turn needs to connect to the same Gorilla server on windows that was being used by the Gorilla Player app. 

This time around, the changes will be visible in my app on simulator & not the gorilla app. 

I get it all now, but we do need to work on the documentation. It's not easy enough for a layman to read through it & understand what to expect in one go. 

I will make sure that I have this covered in my version of that SDK blog. You can then review & use it if found Okay. 

Thanks 
ST

**Comment by jpbrocca** [comment]
Yes @supreettare we need to improve our docs for sure.

Please let me know when you have this ready for review.

Thanks a lot for your help and feedback!

Cheers,
JP

**Comment by supreettare** [comment]
I will Thanks 
Does the Converter work with Gorilla? 

`   <Label x:Name="txtUserName" Grid.Row="0" Grid.Column="1" HorizontalOptions="Start" VerticalOptions="Start" Text="{Binding Question.By.Name, Converter={StaticResource LowerToUpperConverter}}" FontAttributes="Bold" TextColor="#0c0c0c"/>`

This is not rendering,  if I remove the converter call it works

**Comment by LeoHere** [comment]
Yes they work. How is the converter defined and where?

**Comment by LeoHere** [comment]
Regarding the original issue with the WebSite project, I already fixed it. You should get it in the next release.

**Comment by supreettare** [comment]
It's defined in the PCL project inside a directory called Converters & under the namespace City.Converters 
![image](https://cloud.githubusercontent.com/assets/284847/13461507/ee47f0f0-e0a7-11e5-9d6d-5d08573b6eb6.png)

![image](https://cloud.githubusercontent.com/assets/284847/13461514/fde9d212-e0a7-11e5-86e2-d9e7103ebee0.png)

**Comment by LeoHere** [comment]
Sorry, what I meant was where is the converter defined within the XAML? is it in the App.xaml, is it in the current page? Can you show me that.

In the following XAML piece
~~~
<Label x:Name="txtUserName" Grid.Row="0" Grid.Column="1" HorizontalOptions="Start" VerticalOptions="Start" Text="{Binding Question.By.Name, Converter={StaticResource LowerToUpperConverter}}" FontAttributes="Bold" TextColor="#0c0c0c"/>
~~~
If you leave the binding without the converter the sample data for Quesion.by.name is indeed displayed?

**Comment by supreettare** [comment]
![image](https://cloud.githubusercontent.com/assets/284847/13461894/6e41d4fe-e0aa-11e5-8f0f-f71640e9e80d.png)
This is how it is defined. It's on the same content page. & yes If I leave the converter bit, I do see the label rendering fine on the player. 

I have also updated the Gorilla.Json to find City.Converters as valid assembly. 

Anything you spot that I am missing? 

Thanks 
ST

**Comment by LeoHere** [comment]
I think the issue is that the xmlns:converter is omitting the assembly. This is also something the we fix lately (post 0.8.3). Let me know if that fixes your problem.

**Comment by supreettare** [comment]
I am already on Player 0.8.3.0 are you suggesting it was fixed in it?

**Comment by LeoHere** [comment]
No, it was fixed after releasing 0.8.3. Did specifying  the assembly explicitly fixed the issue?

**Comment by supreettare** [comment]
Did you mean in Gorilla.json? 

![image](https://cloud.githubusercontent.com/assets/284847/13489670/592c8448-e14e-11e5-8255-98683d5f1d04.png)

I did update the file as attached. Still no luck.

**Comment by LeoHere** [comment]
No, sorry. I'm talking about the xmlns:converters="clr-namespace:City.Converters" you have in the header of your content view, as shown in this image:

![image](https://cloud.githubusercontent.com/assets/16000584/13490826/77f2fb0a-e10d-11e5-91c5-6c2f3ebde55f.png)

In versions <= 0.8.3 there is an issue with xmlns declarations that omits the assembly. That will be fixed in 0.8.4+.

The workaround would be to include the assembly there, so declaring it as:

xmlns:converters="clr-namespace:City.Converters;assembly=City.Converters"

**Comment by supreettare** [comment]
It worked :)

**Comment by LeoHere** [comment]
Good to know! :+1:

**Comment by supreettare** [comment]
@jpbrocca @LeoHere can I have your email id please? I have completed the changes to the SDK document as suggested, would share it with you. You can also mail me at tare.supreetATgmailDOTcom

**Comment by LeoHere** [comment]
Cool! Thanks. I sent you an email.

**Comment by LeoHere** [comment]
Hi @supreettare! All issues mentioned in this thread were fixed in 0.9.1.2. Closing the issue.
